#include "patches/input_binding/action_registry.h"

#include <algorithm>
#include <array>

namespace input_binding
{
namespace
{
  constexpr auto kActionRegistry = std::to_array<ActionSpec>({
      ActionSpec{{InputActionId::FleetPrimary, "fleet_primary", "SPACE|MOUSE1", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 100},
                 ActionCategory::Fleet,
                 ActionExecutor::FleetSpace,
                 GameFunction::ActionPrimary},
      ActionSpec{{InputActionId::FleetSecondary, "fleet_secondary", "TAB|MOUSE4", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 90},
                 ActionCategory::Fleet,
                 ActionExecutor::FleetSpace,
                 GameFunction::ActionSecondary},
      ActionSpec{{InputActionId::FleetService, "fleet_service", "NONE", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::None, 80},
                 ActionCategory::Fleet,
                 ActionExecutor::FleetSpace},
      ActionSpec{{InputActionId::FleetQueueAdd, "fleet_queue_add", "SPACE|MOUSE1", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::None, 99},
                 ActionCategory::Fleet,
                 ActionExecutor::FleetSpace,
                 GameFunction::ActionQueue},
      ActionSpec{{InputActionId::FleetRecallCancel, "fleet_recall_cancel", "SPACE|MOUSE1", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Fleet, ConflictGroup::None, 98},
                 ActionCategory::Fleet,
                 ActionExecutor::FleetSpace,
                 GameFunction::ActionRecallCancel},
      ActionSpec{{InputActionId::FleetRecall, "fleet_recall", "R|MOUSE3", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::None, 79},
                 ActionCategory::Fleet,
                 ActionExecutor::FleetSpace,
                 GameFunction::ActionRecall},
      ActionSpec{{InputActionId::FleetRepair, "fleet_repair", "R|MOUSE3", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::None, 78},
                 ActionCategory::Fleet,
                 ActionExecutor::FleetSpace,
                 GameFunction::ActionRepair},
      ActionSpec{{InputActionId::FleetViewInfo, "fleet_view_info", "V|MOUSE2", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 70},
                 ActionCategory::Fleet,
                 ActionExecutor::FleetSimple,
                 GameFunction::ActionView},
      ActionSpec{{InputActionId::FleetQueueClear, "fleet_queue_clear", "CTRL-C", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 110},
                 ActionCategory::Fleet,
                 ActionExecutor::FleetSimple,
                 GameFunction::ActionQueueClear},
      ActionSpec{{InputActionId::FleetQueueToggle, "fleet_queue_toggle", "CTRL-Q", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 800},
                 ActionCategory::Fleet,
                 ActionExecutor::FleetQueue,
                 GameFunction::ToggleQueue},
      ActionSpec{{InputActionId::ManualNavigationRefresh, "manual_navigation_refresh", "CTRL-SHIFT-G",
                  TriggerMode::Down, InputPhase::Frame, InputLayer::Diagnostics, ConflictGroup::Diagnostics, 810},
                 ActionCategory::Diagnostics,
                 ActionExecutor::TableDispatch,
                 GameFunction::ManualNavigationRefresh},
      ActionSpec{{InputActionId::SelectShip1, "select_ship1", "1", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 160},
                 ActionCategory::Ships,
                 ActionExecutor::ShipSelection,
                 GameFunction::SelectShip1},
      ActionSpec{{InputActionId::SelectShip2, "select_ship2", "2", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 159},
                 ActionCategory::Ships,
                 ActionExecutor::ShipSelection,
                 GameFunction::SelectShip2},
      ActionSpec{{InputActionId::SelectShip3, "select_ship3", "3", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 158},
                 ActionCategory::Ships,
                 ActionExecutor::ShipSelection,
                 GameFunction::SelectShip3},
      ActionSpec{{InputActionId::SelectShip4, "select_ship4", "4", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 157},
                 ActionCategory::Ships,
                 ActionExecutor::ShipSelection,
                 GameFunction::SelectShip4},
      ActionSpec{{InputActionId::SelectShip5, "select_ship5", "5", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 156},
                 ActionCategory::Ships,
                 ActionExecutor::ShipSelection,
                 GameFunction::SelectShip5},
      ActionSpec{{InputActionId::SelectShip6, "select_ship6", "6", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 155},
                 ActionCategory::Ships,
                 ActionExecutor::ShipSelection,
                 GameFunction::SelectShip6},
      ActionSpec{{InputActionId::SelectShip7, "select_ship7", "7", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 154},
                 ActionCategory::Ships,
                 ActionExecutor::ShipSelection,
                 GameFunction::SelectShip7},
      ActionSpec{{InputActionId::SelectShip8, "select_ship8", "8", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 153},
                 ActionCategory::Ships,
                 ActionExecutor::ShipSelection,
                 GameFunction::SelectShip8},
      ActionSpec{{InputActionId::SelectCurrent, "select_current", "CTRL-SPACE", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Fleet, ConflictGroup::FleetAction, 152},
                 ActionCategory::Ships,
                 ActionExecutor::SelectCurrent,
                 GameFunction::SelectCurrent},
      ActionSpec{{InputActionId::ShowChatSide1, "show_chatside1", "ALT-C", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::ChatOpen, 790},
                 ActionCategory::Chat,
                 ActionExecutor::ChatOpen,
                 GameFunction::ShowChatSide1},
      ActionSpec{{InputActionId::ShowChatSide2, "show_chatside2", "`", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::ChatOpen, 789},
                 ActionCategory::Chat,
                 ActionExecutor::ChatOpen,
                 GameFunction::ShowChatSide2},
      ActionSpec{{InputActionId::ShowChat, "show_chat", "C", TriggerMode::Down, InputPhase::Frame, InputLayer::Global,
                  ConflictGroup::ChatOpen, 780},
                 ActionCategory::Chat,
                 ActionExecutor::ChatOpen,
                 GameFunction::ShowChat},
      ActionSpec{{InputActionId::SelectChatGlobal, "select_chatglobal", "CTRL-1", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::ChatChannel, 760},
                 ActionCategory::Chat,
                 ActionExecutor::ChatChannel,
                 GameFunction::SelectChatGlobal},
      ActionSpec{{InputActionId::SelectChatAlliance, "select_chatalliance", "CTRL-2", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::ChatChannel, 750},
                 ActionCategory::Chat,
                 ActionExecutor::ChatChannel,
                 GameFunction::SelectChatAlliance},
      ActionSpec{{InputActionId::SelectChatPrivate, "select_chatprivate", "CTRL-3", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::ChatChannel, 740},
                 ActionCategory::Chat,
                 ActionExecutor::ChatChannel,
                 GameFunction::SelectChatPrivate},
      ActionSpec{{InputActionId::MoveLeft, "move_left", "A", TriggerMode::Down, InputPhase::Frame, InputLayer::Global,
                  ConflictGroup::OfficerCanvas, 730},
                 ActionCategory::Navigation,
                 ActionExecutor::OfficerCanvas,
                 GameFunction::MoveLeft},
      ActionSpec{{InputActionId::MoveRight, "move_right", "D", TriggerMode::Down, InputPhase::Frame, InputLayer::Global,
                  ConflictGroup::OfficerCanvas, 720},
                 ActionCategory::Navigation,
                 ActionExecutor::OfficerCanvas,
                 GameFunction::MoveRight},
      ActionSpec{{InputActionId::HotkeysDisable, "hotkeys_disable", "CTRL-ALT-MINUS", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::GlobalControl, 1000},
                 ActionCategory::System,
                 ActionExecutor::GlobalControl,
                 GameFunction::DisableHotKeys},
      ActionSpec{{InputActionId::HotkeysEnable, "hotkeys_enable", "CTRL-ALT-=", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::GlobalControl, 1000},
                 ActionCategory::System,
                 ActionExecutor::GlobalControl,
                 GameFunction::EnableHotKeys},
      ActionSpec{{InputActionId::LogDebug, "log_debug", "CTRL-SHIFT-F9", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Diagnostics, ConflictGroup::FrameDispatch, 190},
                 ActionCategory::Diagnostics,
                 ActionExecutor::TableDispatch,
                 GameFunction::LogLevelDebug},
      ActionSpec{{InputActionId::ZoomIn, "zoom_in", "Q", TriggerMode::Pressed, InputPhase::NavigationZoomUpdate,
                  InputLayer::Zoom, ConflictGroup::Zoom, 100},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::ZoomIn},
      ActionSpec{{InputActionId::ZoomOut, "zoom_out", "E", TriggerMode::Pressed, InputPhase::NavigationZoomUpdate,
                  InputLayer::Zoom, ConflictGroup::Zoom, 100},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::ZoomOut},
      ActionSpec{{InputActionId::ZoomPreset1, "zoom_preset1", "F1", TriggerMode::Down, InputPhase::NavigationZoomUpdate,
                  InputLayer::Zoom, ConflictGroup::Zoom, 150},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::ZoomPreset1},
      ActionSpec{{InputActionId::ZoomPreset2, "zoom_preset2", "F2", TriggerMode::Down, InputPhase::NavigationZoomUpdate,
                  InputLayer::Zoom, ConflictGroup::Zoom, 149},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::ZoomPreset2},
      ActionSpec{{InputActionId::ZoomPreset3, "zoom_preset3", "F3", TriggerMode::Down, InputPhase::NavigationZoomUpdate,
                  InputLayer::Zoom, ConflictGroup::Zoom, 148},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::ZoomPreset3},
      ActionSpec{{InputActionId::ZoomPreset4, "zoom_preset4", "F4", TriggerMode::Down, InputPhase::NavigationZoomUpdate,
                  InputLayer::Zoom, ConflictGroup::Zoom, 147},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::ZoomPreset4},
      ActionSpec{{InputActionId::ZoomPreset5, "zoom_preset5", "F5", TriggerMode::Down, InputPhase::NavigationZoomUpdate,
                  InputLayer::Zoom, ConflictGroup::Zoom, 146},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::ZoomPreset5},
      ActionSpec{{InputActionId::ZoomMin, "zoom_min", "BACKSPACE", TriggerMode::Down, InputPhase::NavigationZoomUpdate,
                  InputLayer::Zoom, ConflictGroup::Zoom, 140},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::ZoomMin},
      ActionSpec{{InputActionId::ZoomMax, "zoom_max", "MINUS", TriggerMode::Down, InputPhase::NavigationZoomUpdate,
                  InputLayer::Zoom, ConflictGroup::Zoom, 139},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::ZoomMax},
      ActionSpec{{InputActionId::ZoomReset, "zoom_reset", "=", TriggerMode::Down, InputPhase::NavigationZoomUpdate,
                  InputLayer::Zoom, ConflictGroup::Zoom, 138},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::ZoomReset},
      ActionSpec{{InputActionId::SetZoomPreset1, "set_zoom_preset1", "SHIFT-F1", TriggerMode::Down,
                  InputPhase::NavigationZoomUpdate, InputLayer::Zoom, ConflictGroup::Zoom, 220},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::SetZoomPreset1},
      ActionSpec{{InputActionId::SetZoomPreset2, "set_zoom_preset2", "SHIFT-F2", TriggerMode::Down,
                  InputPhase::NavigationZoomUpdate, InputLayer::Zoom, ConflictGroup::Zoom, 219},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::SetZoomPreset2},
      ActionSpec{{InputActionId::SetZoomPreset3, "set_zoom_preset3", "SHIFT-F3", TriggerMode::Down,
                  InputPhase::NavigationZoomUpdate, InputLayer::Zoom, ConflictGroup::Zoom, 218},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::SetZoomPreset3},
      ActionSpec{{InputActionId::SetZoomPreset4, "set_zoom_preset4", "SHIFT-F4", TriggerMode::Down,
                  InputPhase::NavigationZoomUpdate, InputLayer::Zoom, ConflictGroup::Zoom, 217},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::SetZoomPreset4},
      ActionSpec{{InputActionId::SetZoomPreset5, "set_zoom_preset5", "SHIFT-F5", TriggerMode::Down,
                  InputPhase::NavigationZoomUpdate, InputLayer::Zoom, ConflictGroup::Zoom, 216},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::SetZoomPreset5},
      ActionSpec{{InputActionId::SetZoomDefault, "set_zoom_default", "CTRL-=", TriggerMode::Down,
                  InputPhase::NavigationZoomUpdate, InputLayer::Zoom, ConflictGroup::Zoom, 215},
                 ActionCategory::Camera,
                 ActionExecutor::Zoom,
                 GameFunction::SetZoomDefault},
      ActionSpec{{InputActionId::Quit, "quit", "F10", TriggerMode::Down, InputPhase::Frame, InputLayer::Global,
                  ConflictGroup::GlobalControl, 900},
                 ActionCategory::System,
                 ActionExecutor::GlobalControl,
                 GameFunction::Quit},
      ActionSpec{{InputActionId::UiScaleUp, "ui_scale_up", "PGUP", TriggerMode::Pressed, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 340},
                 ActionCategory::Interface,
                 ActionExecutor::TableDispatch,
                 GameFunction::UiScaleUp},
      ActionSpec{{InputActionId::UiScaleDown, "ui_scale_down", "PGDOWN", TriggerMode::Pressed, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 330},
                 ActionCategory::Interface,
                 ActionExecutor::TableDispatch,
                 GameFunction::UiScaleDown},
      ActionSpec{{InputActionId::UiViewerScaleUp, "ui_viewer_scale_up", "SHIFT-PGUP", TriggerMode::Pressed,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 320},
                 ActionCategory::Interface,
                 ActionExecutor::TableDispatch,
                 GameFunction::UiViewerScaleUp},
      ActionSpec{{InputActionId::UiViewerScaleDown, "ui_viewer_scale_down", "SHIFT-PGDOWN", TriggerMode::Pressed,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 310},
                 ActionCategory::Interface,
                 ActionExecutor::TableDispatch,
                 GameFunction::UiViewerScaleDown},
      ActionSpec{{InputActionId::LogOff, "log_off", "CTRL-SHIFT-F12", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Diagnostics, ConflictGroup::FrameDispatch, 230},
                 ActionCategory::Diagnostics,
                 ActionExecutor::TableDispatch,
                 GameFunction::LogLevelOff},
      ActionSpec{{InputActionId::LogError, "log_error", "CTRL-SHIFT-F11", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Diagnostics, ConflictGroup::FrameDispatch, 220},
                 ActionCategory::Diagnostics,
                 ActionExecutor::TableDispatch,
                 GameFunction::LogLevelError},
      ActionSpec{{InputActionId::LogWarn, "log_warn", "CTRL-SHIFT-F10", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Diagnostics, ConflictGroup::FrameDispatch, 210},
                 ActionCategory::Diagnostics,
                 ActionExecutor::TableDispatch,
                 GameFunction::LogLevelWarn},
      ActionSpec{{InputActionId::LogInfo, "log_info", "CTRL-SHIFT-F8", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Diagnostics, ConflictGroup::FrameDispatch, 200},
                 ActionCategory::Diagnostics,
                 ActionExecutor::TableDispatch,
                 GameFunction::LogLevelInfo},
      ActionSpec{{InputActionId::LogTrace, "log_trace", "CTRL-SHIFT-F7", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Diagnostics, ConflictGroup::FrameDispatch, 180},
                 ActionCategory::Diagnostics,
                 ActionExecutor::TableDispatch,
                 GameFunction::LogLevelTrace},
      ActionSpec{{InputActionId::ShowQTrials, "show_qtrials", "SHIFT-Q", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 590},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowQTrials},
      ActionSpec{{InputActionId::ShowBookmarks, "show_bookmarks", "B", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 580},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowBookmarks},
      ActionSpec{{InputActionId::ShowLookup, "show_lookup", "L", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 570},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowLookup},
      ActionSpec{{InputActionId::ShowRefinery, "show_refinery", "SHIFT-F", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 560},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowRefinery},
      ActionSpec{{InputActionId::ShowFactions, "show_factions", "F", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 550},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowFactions},
      ActionSpec{{InputActionId::ShowStationExterior, "show_stationexterior", "SHIFT-G", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 540},
                 ActionCategory::Navigation,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShoWStationExterior},
      ActionSpec{{InputActionId::ShowGalaxy, "show_galaxy", "G", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 530},
                 ActionCategory::Navigation,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowGalaxy},
      ActionSpec{{InputActionId::ShowStationInterior, "show_stationinterior", "SHIFT-H", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 520},
                 ActionCategory::Navigation,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowStationInterior},
      ActionSpec{{InputActionId::ShowSystem, "show_system", "H", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 510},
                 ActionCategory::Navigation,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowSystem},
      ActionSpec{{InputActionId::ShowArtifacts, "show_artifacts", "SHIFT-I", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 500},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowArtifacts},
      ActionSpec{{InputActionId::ShowInventory, "show_inventory", "I", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 490},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowInventory},
      ActionSpec{{InputActionId::ShowMissions, "show_missions", "M", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 480},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowMissions},
      ActionSpec{{InputActionId::ShowResearch, "show_research", "U", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 470},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowResearch},
      ActionSpec{{InputActionId::ShowScrapYard, "show_scrapyard", "Y", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 460},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowScrapYard},
      ActionSpec{{InputActionId::ShowOfficers, "show_officers", "SHIFT-O", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 450},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowOfficers},
      ActionSpec{{InputActionId::ShowCommander, "show_commander", "O", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 440},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowCommander},
      ActionSpec{{InputActionId::ShowAwayTeam, "show_awayteam", "T", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 430},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowAwayTeam},
      ActionSpec{{InputActionId::ShowEvents, "show_events", "SHIFT-E", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 420},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowEvents},
      ActionSpec{{InputActionId::ShowExoComp, "show_exocomp", "X", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 410},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowExoComp},
      ActionSpec{{InputActionId::ShowDaily, "show_daily", "Z", TriggerMode::Down, InputPhase::Frame, InputLayer::Global,
                  ConflictGroup::FrameDispatch, 400},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowDaily},
      ActionSpec{{InputActionId::ShowGifts, "show_gifts", "/", TriggerMode::Down, InputPhase::Frame, InputLayer::Global,
                  ConflictGroup::FrameDispatch, 390},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowGifts},
      ActionSpec{{InputActionId::ShowAlliance, "show_alliance", "ALT-'", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 380},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowAlliance},
      ActionSpec{{InputActionId::ShowAllianceHelp, "show_alliance_help", "SHIFT-'", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 370},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowAllianceHelp},
      ActionSpec{{InputActionId::ShowAllianceArmada, "show_alliance_armada", "CTRL-'", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 360},
                 ActionCategory::Panels,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowAllianceArmada},
      ActionSpec{{InputActionId::ShowSettings, "show_settings", "SHIFT-S", TriggerMode::Down, InputPhase::Frame,
                  InputLayer::Global, ConflictGroup::FrameDispatch, 350},
                 ActionCategory::Interface,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowSettings},
      ActionSpec{{InputActionId::TogglePreviewLocate, "toggle_preview_locate", "CTRL-R", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 300},
                 ActionCategory::Interface,
                 ActionExecutor::TableDispatch,
                 GameFunction::TogglePreviewLocate},
      ActionSpec{{InputActionId::TogglePreviewRecall, "toggle_preview_recall", "CTRL-T", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 290},
                 ActionCategory::Interface,
                 ActionExecutor::TableDispatch,
                 GameFunction::TogglePreviewRecall},
      ActionSpec{{InputActionId::ToggleCargoDefault, "toggle_cargo_default", "ALT-1", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 280},
                 ActionCategory::Ships,
                 ActionExecutor::TableDispatch,
                 GameFunction::ToggleCargoDefault},
      ActionSpec{{InputActionId::ToggleCargoPlayer, "toggle_cargo_player", "ALT-2", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 270},
                 ActionCategory::Ships,
                 ActionExecutor::TableDispatch,
                 GameFunction::ToggleCargoPlayer},
      ActionSpec{{InputActionId::ToggleCargoStation, "toggle_cargo_station", "ALT-3", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 260},
                 ActionCategory::Ships,
                 ActionExecutor::TableDispatch,
                 GameFunction::ToggleCargoStation},
      ActionSpec{{InputActionId::ToggleCargoHostile, "toggle_cargo_hostile", "ALT-4", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 250},
                 ActionCategory::Ships,
                 ActionExecutor::TableDispatch,
                 GameFunction::ToggleCargoHostile},
      ActionSpec{{InputActionId::ToggleCargoArmada, "toggle_cargo_armada", "ALT-5", TriggerMode::Down,
                  InputPhase::Frame, InputLayer::Global, ConflictGroup::FrameDispatch, 240},
                 ActionCategory::Ships,
                 ActionExecutor::TableDispatch,
                 GameFunction::ToggleCargoArmada},
      ActionSpec{{InputActionId::ShowShips, "show_ships", "N", TriggerMode::Down, InputPhase::Frame, InputLayer::Global,
                  ConflictGroup::FrameDispatch, 170},
                 ActionCategory::Ships,
                 ActionExecutor::TableDispatch,
                 GameFunction::ShowShips},
  });

  static_assert(kActionRegistry.size() == static_cast<size_t>(InputActionId::Max));
} // namespace

std::span<const ActionSpec> ActionRegistry()
{ return kActionRegistry; }

const ActionSpec* FindAction(const InputActionId id)
{
  const auto registry = ActionRegistry();
  const auto found    = std::ranges::find_if(registry, [id](const auto& spec) { return spec.id == id; });
  return found == registry.end() ? nullptr : &*found;
}

const ActionSpec* FindAction(const std::string_view canonical_key)
{
  const auto registry = ActionRegistry();
  const auto found =
      std::ranges::find_if(registry, [canonical_key](const auto& spec) { return spec.canonical_key == canonical_key; });
  return found == registry.end() ? nullptr : &*found;
}

const ActionSpec* FindActionByGameFunction(const GameFunction game_function)
{
  const auto registry = ActionRegistry();
  const auto found =
      std::ranges::find_if(registry, [game_function](const auto& spec) { return spec.game_function == game_function; });
  return found == registry.end() ? nullptr : &*found;
}

GameFunction ActionGameFunction(const InputActionId id)
{
  if (const auto* spec = FindAction(id); spec) {
    return spec->game_function;
  }
  return GameFunction::Max;
}

} // namespace input_binding
